AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - "vendor/**/*"
    - "spec/**/*"

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 30

Layout/LineLength:
  Max: 120

Style/IfUnlessModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false
